apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: demucs-worker:latest
          imagePullPolicy: Never
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: MINIO_HOST
              value: "minio-service.minio-ns:9000"
          resources:
            requests:
              memory: "6Gi"
              cpu: "1"
